### ISSUE TITLE
Decorator-friendly higher-order component

### ISSUE THREAD

**Issue by jdelman** [podefr/react-debounce-render#10]
With only a few extra hundred bytes, this library could include a higher-order component that is decorator-friendly. It would also then have the same method signature as react-redux's `connect`, React DnD, and other higher-order components: `options => Component => func(Component, options)`

```js
import debounceRender from 'react-debounce-render';

export function debounceComponent(...args) {
  return function(Component) {
    return debounceRender(Component, ...args);
  }
}
```

Then you can attach to a component like:

```js
@connect(state => { prop: state.prop })
@debounceComponent(100, { trailing: true })
export default MyComponent extends Component {}
```

Even if you don't want to use this as a decorator, making the component the sole argument to a bunch of applied partials allows you to export a reusable debouncer with custom options, like:

```js
const myDebouncer = debounceComponent(100, { trailing: true });
export const myDebouncer;
``` 

Not a big deal if it's not included in the library, as I'll be using that myself... but I thought it could be helpful for other people as well. Thanks for this great utility!

**Comment by podefr** [comment]
hey Josh, thanks for the suggestion, I really like that idea!

just to confirm I'm getting this right, there is not breaking change to the current API here, but it would provide users with an additional interface so we can use decorators or do partial application?

**Comment by jdelman** [comment]
@podefr Up to you if you want to make it a breaking change. Since it doesn't add too much code to have the wrapper exported, it's probably fine to add it as an additional interface. I can make a PR later if you'd like.

**Comment by yched** [comment]
+1 ! FWIW, I ended up doing exactly the same HOC on my site :-)

**Comment by podefr** [comment]
Thanks again for the suggestion @jdelman. Given that I don't have an environment setup for using decorators (I should though, I've been waiting for this feature for a long time!), would you be able to suggest a PR with the decorator friendly factory and ideally an integration test in e2e as well?

thanks!

**Comment by jwmann** [comment]
Any update on this?

**Comment by podefr** [comment]
Nop I haven't worked on it, I was hoping that someone who has the need for the feature would suggest a PR so that they can test that the solution is valid too. Are you in this position? :) I can work on it but it will take a couple weeks at least

**Comment by podefr** [comment]
Hi, 

Sorry but I'll have to close this issue. Having further investigating this issue it seems that we're far from having consensus as to what decorators will look like. The risk is too high that we implement a decorator that will only work in a subset of browsers for a limited period of time. I'm happy to revisit when decorator specs get closer to becoming a standard. In the meantime, I would recommend rolling out your own decorators for your needs, which I hope shouldn't be too difficult.
