### ISSUE TITLE
Throttle rather than debounce?

### ISSUE THREAD

**Issue by DanielHeath** [podefr/react-debounce-render#15]
With debounce, you can get 'starvation' where new events keep arriving, preventing you from ever re-rendering.

lodash.throttle allows one re-render per 'wait' period, which I think would still achieve the performance aims of this library without allowing the UI to get stuck.

**Comment by podefr** [comment]
Hi Daniel,

Thanks for the suggestion. Does the `maxWait` option of `_.debounce` address your issue? Doing something like this should ensure that your component gets rendered at least 4 times per second:

```
const debouncedMyReactComponent = debounceRender(MyReactComponent, 100, { 
    maxWait: 250 
});
```

ref: https://lodash.com/docs/#debounce

**Comment by DanielHeath** [comment]
That would do it, yeah. 

Bit of a thing to trip over newcomers, though. Maybe a note in the sample usage section of the readme?

**Comment by podefr** [comment]
Hi Daniel,

I've updated the documentation to add the maxWait example. It also mentions that lodash debounce is used under the hood and that it can be configured. I hope this addresses the issue you raised?

Let me know if I can close this ticket and thanks for use this lib!

**Comment by DanielHeath** [comment]
Looking good!
