### ISSUE TITLE
Could you please share changes for the latest v6.0.0 release?

### ISSUE THREAD

**Issue by gr2m** [podefr/react-debounce-render#17]
I use it in the the Octokit docs site at https://octokit.github.io/rest.js/. I don't have tests for the docs site, so I'm not sure if the upgrade could break anything. It would be helpful to know what you changed with the latest release.

Thanks for your work on this library 👍

**Comment by podefr** [comment]
Thanks gr2m! I have a changelog in the README: https://github.com/podefr/react-debounce-render#600---feb-04-2020

The change should fix an issue where static properties in the original components weren't hoisted to the debounced component once wrapped with this HoC. More details here: https://github.com/podefr/react-debounce-render/pulls?q=is%3Apr+is%3Aclosed

The change should be completely backwards compatible, I just don't follow SEMVER very strictly :)

let me know if this helps so I can close, and thanks again for using this lib!

**Comment by gr2m** [comment]
🤦‍♂  sorry that I missed the changelog in the README! Thank you for your swift response!
