### ISSUE TITLE
full Typescript support

### ISSUE THREAD

**Issue by scottschafer** [podefr/react-debounce-render#18]
This may just be something stupid I'm not getting (I'm not that skilled with HOCs), but here's my issue. I have a component declared in Typescript like this.

`class DataGrid extends React.Component<DataGridProps>`

I can export it like this:

`const debouncedComponent = debounceRender(DataGrid, 1000, {})`

It seems to work. But when I import and use this version in a TSX, I lose all typing on the properties. I've tried the Typescript version 'react-debounce-render' but no luck there either.

How can I accomplish this?

**Comment by podefr** [comment]
version 8.0.0+ now has native typescript support
