### ISSUE TITLE
[Question] Should this work with react-native?

### ISSUE THREAD

**Issue by filipef101** [podefr/react-debounce-render#19]
I tested it and doesn't seem to work, tested having a setinterval with a lower value (100m) than the debounce value(1000ms), and with a console log on the render and it was being called every 100 ms

**Comment by podefr** [comment]
it's a good question but I don't know, not having used react-native. Would you be able to setup a skeleton git with a sample react native app and react-debounce-render and I'll take a look?

**Comment by filipef101** [comment]
Yes it works, forgot about this issue.
Altought I ended up borrowing the logic and not use the package as just needed for a specific view.
