### ISSUE TITLE
Make composable with lodash.flowRight & ramda.compose

### ISSUE THREAD

**Issue by CurriedFloat** [podefr/react-debounce-render#21]
Hi, debounceRender is great, just wished it was composable.
I'm currently wrapping debounceRender so it can be used with compose.

```
<--- wrapper --->
import debounceRender from 'react-debounce-render';

export const debounce = (wait = 0, options = {}) => component =>  
  debounceRender(component, wait, options);

<--- example usage --->
export default compose(
  withStyles(styles), 
  connect(
    mapStateToProps,  
    mapDispatchToProps
  ),  
  debounce(200, {maxWait: 400})
)(SomeComponent);
```

[react docs: higher-order-components.html#convention-maximizing-composability](https://reactjs.org/docs/higher-order-components.html#convention-maximizing-composability)

**Comment by podefr** [comment]
Hi, thanks for the suggestion! I think it makes perfect sense. Would you be ok creating a PR to expedite the fix?

**Comment by CurriedFloat** [comment]
> Hi, thanks for the suggestion! I think it makes perfect sense. Would you be ok creating a PR to expedite the fix?

Yes, sure :)

**Comment by podefr** [comment]
thanks for the PR! I added a few tests, updated the changelog and published version 7.0.0. Please let me know if everything works as expected for you and I'll close the issue. Thanks!

**Comment by CurriedFloat** [comment]
Updated to 7.0.0 and switched to the `debounce` version and everything seems to be working as expected. 
Thanks! :)

**Comment by podefr** [comment]
👍
