### ISSUE TITLE
README inaccurate with { leading: false }?

### ISSUE THREAD

**Issue by spidgorny** [podefr/react-debounce-render#24]
> To trigger the debounce on the leader edge:
> ```import debounceRender from 'react-debounce-render';```
> ```const debouncedMyReactComponent = debounceRender(MyReactComponent, 100, { leading: false });```

Should it be ```{ leading: true }``` maybe?

**Comment by podefr** [comment]
thanks, should be fixed now!

**Comment by MITCHELLNEAL1** [comment]
cool
