### ISSUE TITLE
Lack of TS support while installing `react-debounce-render` from `npm`. 

### ISSUE THREAD

**Issue by robert-orlinski** [podefr/react-debounce-render#35]
Hello!

I wanted to check how the library works since it looks like something that exactly and quickly solves my current challenge but after installing it from `npm` (version 8.0.1), as I see TS declarations are not included in downloaded package.

Is there something not right with the package published on `npm` or I don't know about something? 

Thank you in advance :)

**Comment by podefr** [comment]
wow I can't believe I missed that, thanks so much for raising the issue and thanks for using react-debounce-render!

I just published  8.0.2 which should now include the type definitions, could you test and let me know if all works as intended? 

Thanks!

**Comment by robert-orlinski** [comment]
It works. Thank you!

**Comment by podefr** [comment]
thanks for raising the issue!
