### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by TheSharpieOne** [podefr/react-debounce-render#4]
Please support react 16 in your package.json. You also might want to consider moving react to a peerDependency.

**Comment by podefr** [comment]
thanks @TheSharpieOne for the suggestion. I moved react to the peerDependencies and I'm allowing versions greater than 15, so 16 is now supported. I published v4.0.0 to npm, let me know if it addresses your issue. Thanks!

**Comment by TheSharpieOne** [comment]
Awesome, works great. Thanks!

**Comment by podefr** [comment]
Thanks!
