### ISSUE TITLE
No reason to depend on both 'lodash' and 'lodash.debounce' ?

### ISSUE THREAD

**Issue by yched** [podefr/react-debounce-render#8]
The package depends on lodash/debounce, and thus doesn't need the whole lodash lib in addition ?

**Comment by podefr** [comment]
Hi Yves, as you've mentioned this issue has been discussed already in Pull Request #7. May I close this issue as well?

Thanks,
Olivier

**Comment by yched** [comment]
Well, as I wrote in PR #7, the current situation is still weird - package.json requires both lodash and lodash.debonuce, but only needs one of the two.

I was too quick in titling this issue (it's lodash.debounce that is currently unused), but it still seems like something needs fixing ?

**Comment by yched** [comment]
Also, PR #7 reverted using lodash.debounce in favor of using the complete lodash on the basis that lodash.debounce hadn't been updated for two years. 

However, it does look like the code in lodash.debounce 4.0.8 is the exact same that ships with lodash 4.17.10 - i.e. debounce hasn't been touched in two years, so it's totally normal that lodash.debounce hasn't been republished since then.

(there is indeed a 2018 commit on debounce in lodash master, but it's not in release 4.17.10)

--> Looks like we could revert PR #7 and just go back to using lodash.debounce ?
Importing the minimal dependency is always better than importing a huge bundle and relying on tree-shaking :-)

**Comment by amio** [comment]
Agree with @yched, that's a significant difference in [install size](https://packagephobia.now.sh/result?p=react-debounce-render):

![image](https://user-images.githubusercontent.com/215282/45467998-0cd21d80-b755-11e8-85f7-abc130a9510b.png)

**Comment by podefr** [comment]
sorry for the oversight, it definitely looks like in trying to resolve the bundle size issue I ended up leaving both lodash and lodash.debounce as deps. When I investigated it looked like lodash.debounce was behind. I checked again and you're right they're both the same version. I'll switch back to using the lodash.debounce instead, sorry about that!

**Comment by podefr** [comment]
I just pushed version 5.0.0 which removes the dependency on lodash in favor of lodash.debounce.
I'll close this issue, feel free to reopen if you're still seeing the bundle size issue. 

Thanks all for your help!
